#!/usr/bin/env ruby

require 'landscapist'
require 'thor'

class LandscapistCLI < Thor

  desc 'print FILE', "Print the API tree"
  def print(file)
    puts Landscapist.parse(file).tree
  end

  desc 'swagger FILE', "Print the API swagger definition"
  def swagger(file)
    puts Landscapist.parse(file).swagger
  end

  desc 'typescript FILE', "Print the API typescript definitions"
  def typescript(file)
    puts Landscapist.parse(file).typescript
  end

  desc 'server FILE', "Start web server"
  method_option :port, type: :numeric, default: 9292, aliases: '-p', desc: 'http listen port'
  def server(file)
    require 'landscapist/viewer/swagger'
    system(%Q[(sleep 1 ; open http://localhost:#{options[:port]}/) &]) if RUBY_PLATFORM =~ /darwin/i
    Rack::Server.start( app: Rack::ShowExceptions.new(Landscapist::Viewer::Swagger.new(file)), Port: options[:port] )
  end

end

LandscapistCLI.start
